# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- automated

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: ./compile.sh KERNEL_ONLY=yes  BOARD=orangepi3 BRANCH=next KERNEL_CONFIGURE=no
  displayName: 'Compile'


